In [25]:
import numpy as np
import pandas as pd
import math

data = pd.read_excel(r"./data/problem02_data.xlsx")
data = data.values
data = data[:, 1:8]
data

array([[1.64905280e+02, 1.62604000e+03, 1.27000000e+00, 2.48600000e+02,
        1.20060000e+03, 8.43750000e+02, 6.20000000e-01],
       [1.70391189e+02, 1.75467000e+03, 1.29000000e+00, 2.57900000e+02,
        1.25350000e+03, 8.66670000e+02, 8.30000000e-01],
       [1.78782390e+02, 1.86105000e+03, 1.90000000e+00, 2.75300000e+02,
        1.31660000e+03, 9.31470000e+02, 9.80000000e-01],
       [1.90831939e+02, 1.93213000e+03, 1.20000000e+00, 2.98600000e+02,
        1.38740000e+03, 9.38740000e+02, 1.13000000e+00],
       [2.07823412e+02, 2.05238000e+03, 1.08000000e+00, 3.31200000e+02,
        1.47320000e+03, 9.49110000e+02, 1.30000000e+00]])

In [26]:
emission = data.copy()
for i in range(0, 5):
    for j in range(0, 6):
        emission[i, j] = emission[i, j] / emission[i, j + 1]
emission

array([[1.01415266e-01, 1.28034646e+03, 5.10860821e-03, 2.07063135e-01,
        1.42293333e+00, 1.36088710e+03, 6.20000000e-01],
       [9.71072563e-02, 1.36020930e+03, 5.00193874e-03, 2.05743917e-01,
        1.44634059e+00, 1.04418072e+03, 8.30000000e-01],
       [9.60653340e-02, 9.79500000e+02, 6.90156193e-03, 2.09099195e-01,
        1.41346474e+00, 9.50479592e+02, 9.80000000e-01],
       [9.87676497e-02, 1.61010833e+03, 4.01875419e-03, 2.15222719e-01,
        1.47793851e+00, 8.30743363e+02, 1.13000000e+00],
       [1.01259714e-01, 1.90035185e+03, 3.26086957e-03, 2.24816725e-01,
        1.55219100e+00, 7.30084615e+02, 1.30000000e+00]])

In [27]:
def F(a, b):
    if a == b:
        return a
    else:
        return (a - b) / (math.log(a) - math.log(b))


res_LMDI = emission.copy()
for i in range(1, 5):
    for j in range(0, 7):
        res_LMDI[i, j] = F(data[i, 0], data[i - 1, 0]) * math.log(emission[i, j] / emission[i - 1, j])
res_LMDI = res_LMDI[1:, :]
res_LMDI

array([[ -7.27654712,  10.14313337,  -3.53729944,  -1.07142354,
          2.73513257, -44.40675558,  48.89966918],
       [ -1.88300631, -57.31481937,  56.19253675,   2.82365627,
         -4.01344609, -16.4116936 ,  28.99797283],
       [  5.12502904,  91.81929285, -99.90382805,   5.33250142,
          8.24026737, -24.87468575,  26.31097231],
       [  4.96394261,  33.01607402, -41.62987335,   8.68783666,
          9.76497574, -25.72966061,  27.91817822]])

In [28]:
delta_C = []
for i in range(1,5):
    delta_C.append(data[i,0]-data[i-1,0])
delta_C = np.asarray(delta_C)
weight_LMDI = res_LMDI.copy()
for i in range(0,4):
    for j in range(0,7):
       weight_LMDI[i,j]/=delta_C[i]
weight_LMDI

array([[-1.32640671,  1.84894291, -0.64479727, -0.19530463,  0.49857414,
        -8.0946935 ,  8.91368507],
       [-0.22440249, -6.83034798,  6.6966028 ,  0.33650206, -0.47829224,
        -1.95582189,  3.45575974],
       [ 0.42532953,  7.62014341, -8.29108429,  0.44254779,  0.6838652 ,
        -2.0643665 ,  2.18356487],
       [ 0.29214315,  1.9430966 , -2.45004495,  0.51130567,  0.57469859,
        -1.51426896,  1.64306989]])

In [29]:
delta_C

array([ 5.48590945,  8.39120049, 12.04954919, 16.99147329])